### ISSUE TITLE
Error on android device while running

### ISSUE THREAD

**Issue by iamCoderGod** [vakrilov/nativescript-physics-js#3]
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
Error calling module function 

Error: com.tns.NativeScriptException: Failed to find module: "application", relative to: /app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:197)
    com.tns.Module.resolvePath(Module.java:62)
    com.tns.Platform.runModule(Native Method)
    com.tns.Platform.runModule(Platform.java:184)
    com.tns.Platform.run(Platform.java:176)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:784)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4567)
    android.app.ActivityThread.access$1500(ActivityThread.java:151)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1371)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:135)
    android.app.ActivityThread.main(ActivityThread.java:5268)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
File: "<unknown>, line: 1, column: 119

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 120
	Frame: function:'', file:'/data/data/org.nativescript.demo/files/app/app.js', line: 1, column: 79

	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4570)
	at android.app.ActivityThread.access$1500(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1371)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5268)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
Caused by: com.tns.NativeScriptException: 
Error calling module function 

Error: com.tns.NativeScriptException: Failed to find module: "application", relative to: /app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:197)
    com.tns.Module.resolvePath(Module.java:62)
    com.tns.Platform.runModule(Native Method)
    com.tns.Platform.runModule(Platform.java:184)
    com.tns.Platform.run(Platform.java:176)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:784)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4567)
    android.app.ActivityThread.access$1500(ActivityThread.java:151)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1371)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:135)
    android.app.ActivityThread.main(ActivityThread.java:5268)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
File: "<unknown>, line: 1, column: 119

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 120
	Frame: function:'', file:'/data/data/org.nativescript.demo/files/app/app.js', line: 1, column: 79

	at com.tns.Platform.runModule(Native Method)
	at com.tns.Platform.runModule(Platform.java:184)
	at com.tns.Platform.run(Platform.java:176)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:784)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4567)
	... 9 more

**Comment by vakrilov** [comment]
The `Failed to find module: "application"` error message indicates a problem with the `tns-core-modules` package. Can you please check if you have it and all your dependencies in the `package.json` are installed.

**Comment by memePushpendu** [comment]
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.dragonRunner",
    "tns-android": {
      "version": "3.1.1"
    }
  },
  "dependencies": {
    "nativescript-physics-js": "^1.0.5",
    "nativescript-theme-core": "~1.0.2",
    "tns-core-modules": "3.1.0"
  },
  "devDependencies": {
    "babel-traverse": "6.25.0",
    "babel-types": "6.25.0",
    "babylon": "6.17.4",
    "lazy": "1.0.11"
  }
}

This is my package.json and all dependencies are installed . Do you need any more information to solve it ? . Please help me . I am stuck .

**Comment by memePushpendu** [comment]
I don't know if this is same as the previous error but currently i am having this. 

finished with reading lines with js files
:asbg:generateBindings
Exception in thread "main" java.lang.ClassNotFoundException: Class: org.nativescript.widgets.image.Worker.OnImageLoadedListener
        at org.nativescript.staticbindinggenerator.Generator.getClass(Generator.java:709)
        at org.nativescript.staticbindinggenerator.Generator.collectInterfaceMethods(Generator.java:661)
        at org.nativescript.staticbindinggenerator.Generator.getPublicApi(Generator.java:212)
        at org.nativescript.staticbindinggenerator.Generator.writeBinding(Generator.java:326)
        at org.nativescript.staticbindinggenerator.Generator.generateBinding(Generator.java:117)
        at org.nativescript.staticbindinggenerator.Generator.processRows(Generator.java:157)
        at org.nativescript.staticbindinggenerator.Generator.generateBindings(Generator.java:77)
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:54)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:15)
:asbg:generateBindings FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/home/codergod/development/tns/dragonRunner/platforms/android/build-tools/android-static-binding-generator/build.gradle' line: 254

* What went wrong:
Execution failed for task ':asbg:generateBindings'.
> Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 14.388 secs
Unable to sync files. Error is: Multiple errors were thrown:
Command ./gradlew failed with exit code 1

**Comment by memePushpendu** [comment]
Can you please help . Or creating a plugin is all where your responsiblity ends , you think ?

**Comment by iamCoderGod** [comment]
Give me your email I am sending you the project code. Please fix it for me .

On 16-Aug-2017 12:20 pm, memePushpendu <notifications@github.com> wrote:

Can you please help . Or creating a plugin is all where your responsiblity ends , you think ?

**Comment by vakrilov** [comment]
Hi @memePushpendu and @iamCoderGod 
I have published `nativescript-physics-js@2.0.1` version of the plugin that is compatible with NativeScript 3.1.1. 
Try to update and your build error should be resolved.

**Comment by memePushpendu** [comment]
Thanks , working perfectly fine .

**Comment by memePushpendu** [comment]
But I want some more help . If you can please provide me your email id.  or mail @     ghoshpushpendu@outlook.com

**Comment by memePushpendu** [comment]
b.t.w i am both  @memePushpendu and @iamCoderGod

**Comment by vakrilov** [comment]
I'm glad your problem was solved @iamCoderGod / @memePushpendu.

If you face other problems with the plugin you can open another issue or ultimately open a PR with a fix.
